/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SNS.view.phone.MainView', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.mainview',

    config: {
        itemId: 'mainView',
	tabBarPosition: 'bottom',
        items: [
            {
                xtype: 'formpanel',
		iconCls: 'home',
		title: 'Scan',
                layout: {
                    type: 'vbox'
                },
                items: [
                    {
                        xtype: 'fieldset',
                        title: 'Barcode Scan Test',
                        items: [
                            {
                                xtype: 'textfield',
                                name: 'scanfield'
                            },
                            {
                                xtype: 'segmentedbutton',
                                margin: 25,
                                allowToggle: false,
                                layout: {
                                    pack: 'center',
                                    type: 'hbox'
                                },
                                items: [
                                    {
                                        xtype: 'button',
                                        minWidth: 250,
					ui: 'action-round',
                                        action: 'scan',
                                        text: 'Start Scan'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
			flex: 1,
                        layout: {
                            type: 'fit'
                        },
                        items: [
                            {
                                xtype: 'dataview',
                                id: 'statusView',
                                margin: '0 25 25 25',
                                itemTpl: [
                                    '<div><div class="status {statuscode}">{status}</div><div class="time"><tpl if="elapsed &gt; 0">( {elapsed} ms )</tpl></div></div>'
                                ],
                                store: 'StatusStore'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                id: 'detailview',
		iconCls: 'star',
		title: 'Details',
		disabled: true,
		styleHtmlContent: true,
                flex: 1,
                tpl: [
                    '<tpl for=\".\">',
                    '<tpl if=\"cover\">',
                    '<tpl for=\"cover\">',
                    '<img src=\"{large}\" />',
                    '</tpl>',
		    '</tpl>',
                    '<h1>{title}</h1>',
                    '<h2>{by_statement}</h2>',
                    '<tpl if=\"links\">',
                    'Links:<br /><ul>',
                    '<tpl for=\"links\">',
                    '<li><a href=\"{url}\">{title}</a></li>',
                    '</tpl>',
                    '</ul>',
                    '</tpl>',
                    '</tpl>'
                ]
            }
        ]
    }

});
